# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "958b8b5ec88d055bc57385db58a56d46"
name = "ultimate-cart"
application_url = "https://letting-vanilla-ada-marker.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_markets,read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://super-duper-trout-7797j95x69xwcpwv9-3457.app.github.dev/api/auth"
]
