import { json, type ActionFunctionArgs, type LoaderFunctionArgs } from "@remix-run/node";
import { useLoaderData, useSubmit, Form, useNavigation } from "@remix-run/react";
import {
  Page, Card, BlockStack, Button, Text, InlineStack,
    Badge, Modal, TextField, Select, Banner, EmptyState, Spinner
    } from "@shopify/polaris";
    import { useState, useCallback } from "react";
    import { authenticate } from "../shopify.server";
    import db from "../db.server";

    const MARKET_OPTIONS = [
      { label: "India (INR)", value: "IN", currency: "INR", flag: "🇮🇳" },
        { label: "United States (USD)", value: "US", currency: "USD", flag: "🇺🇸" },
          { label: "United Kingdom (GBP)", value: "GB", currency: "GBP", flag: "🇬🇧" },
            { label: "United Arab Emirates (AED)", value: "AE", currency: "AED", flag: "🇦🇪" },
              { label: "Australia (AUD)", value: "AU", currency: "AUD", flag: "🇦🇺" },
                { label: "Canada (CAD)", value: "CA", currency: "CAD", flag: "🇨🇦" },
                  { label: "Singapore (SGD)", value: "SG", currency: "SGD", flag: "🇸🇬" },
                  ];

                  export async function loader({ request }: LoaderFunctionArgs) {
                    const { session } = await authenticate.admin(request);
                      const markets = await db.market.findMany({
                          where: { shop: session.shop },
                              include: { milestones: true },
                                  orderBy: { createdAt: "asc" },
                                    });
                                      return json({ markets });
                                      }

                                      export async function action({ request }: ActionFunctionArgs) {
                                        const { session } = await authenticate.admin(request);
                                          const formData = await request.formData();
                                            const intent = formData.get("intent");

                                              if (intent === "create") {
                                                  const code = String(formData.get("code"));
                                                      const option = MARKET_OPTIONS.find((o) => o.value === code);
                                                          if (!option) return json({ error: "Invalid market" }, { status: 400 });
                                                              await db.market.upsert({
                                                                    where: { shop_code: { shop: session.shop, code } },
                                                                          update: { enabled: true },
                                                                                create: {
                                                                                        shop: session.shop,
                                                                                                code,
                                                                                                        name: option.label,
                                                                                                                currency: option.currency,
                                                                                                                        flag: option.flag,
                                                                                                                              },
                                                                                                                                  });
                                                                                                                                    }
                                                                                                                                    
                                                                                                                                      if (intent === "toggle") {
                                                                                                                                          const id = String(formData.get("id"));
                                                                                                                                              const enabled = formData.get("enabled") === "true";
                                                                                                                                                  await db.market.update({ where: { id }, data: { enabled: !enabled } });
                                                                                                                                                    }
                                                                                                                                                    
                                                                                                                                                      if (intent === "delete") {
                                                                                                                                                          const id = String(formData.get("id"));
                                                                                                                                                              await db.market.delete({ where: { id } });
                                                                                                                                                                }
                                                                                                                                                                
                                                                                                                                                                  return json({ ok: true });
                                                                                                                                                                  }
                                                                                                                                                                  
                                                                                                                                                                  export default function MarketsPage() {
                                                                                                                                                                    const { markets } = useLoaderData<typeof loader>();
                                                                                                                                                                      const submit = useSubmit();
                                                                                                                                                                        const navigation = useNavigation();
                                                                                                                                                                          const [modalOpen, setModalOpen] = useState(false);
                                                                                                                                                                            const [selectedCode, setSelectedCode] = useState("IN");
                                                                                                                                                                            
                                                                                                                                                                              const existingCodes = markets.map((m) => m.code);
                                                                                                                                                                                const availableOptions = MARKET_OPTIONS.filter((o) => !existingCodes.includes(o.value));
                                                                                                                                                                                
                                                                                                                                                                                  const handleCreate = useCallback(() => {
                                                                                                                                                                                      submit({ intent: "create", code: selectedCode }, { method: "post" });
                                                                                                                                                                                          setModalOpen(false);
                                                                                                                                                                                            }, [selectedCode, submit]);
                                                                                                                                                                                            
                                                                                                                                                                                              return (
                                                                                                                                                                                                  <Page
                                                                                                                                                                                                        title="Markets"
                                                                                                                                                                                                              subtitle="Configure separate cart settings per market"
                                                                                                                                                                                                                    primaryAction={{
                                                                                                                                                                                                                            content: "Add Market",
                                                                                                                                                                                                                                    onAction: () => setModalOpen(true),
                                                                                                                                                                                                                                            disabled: availableOptions.length === 0,
                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                            <BlockStack gap="400">
                                                                                                                                                                                                                                                                    {markets.length === 0 ? (
                                                                                                                                                                                                                                                                              <Card>
                                                                                                                                                                                                                                                                                          <EmptyState
                                                                                                                                                                                                                                                                                                        heading="No markets configured"
                                                                                                                                                                                                                                                                                                                      image="https://cdn.shopify.com/s/files/1/0262/4071/2726/files/emptystate-files.png"
                                                                                                                                                                                                                                                                                                                                    action={{ content: "Add your first market", onAction: () => setModalOpen(true) }}
                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                              <p>Add markets to configure independent cart experiences for each region.</p>
                                                                                                                                                                                                                                                                                                                                                                          </EmptyState>
                                                                                                                                                                                                                                                                                                                                                                                    </Card>
                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                      markets.map((market) => (
                                                                                                                                                                                                                                                                                                                                                                                                                  <Card key={market.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                <InlineStack align="space-between" blockAlign="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <InlineStack gap="300" blockAlign="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Text variant="headingMd" as="h2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {market.flag} {market.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Badge tone={market.enabled ? "success" : "critical"}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {market.enabled ? "Active" : "Disabled"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Badge>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Text as="span" tone="subdued">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {market.milestones.length} milestone{market.milestones.length !== 1 ? "s" : ""}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </InlineStack>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <InlineStack gap="200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Button url={`/app/milestones/${market.code}`}>Configure</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Form method="post">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="hidden" name="intent" value="toggle" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="hidden" name="id" value={market.id} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="hidden" name="enabled" value={String(market.enabled)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button submit tone={market.enabled ? "critical" : undefined} variant="plain">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {market.enabled ? "Disable" : "Enable"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Form method="post">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input type="hidden" name="intent" value="delete" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="hidden" name="id" value={market.id} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Button submit tone="critical" variant="plain">Delete</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </InlineStack>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </InlineStack>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </BlockStack>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Modal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        open={modalOpen}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClose={() => setModalOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title="Add Market"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                primaryAction={{ content: "Add Market", onAction: handleCreate }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        secondaryActions={[{ content: "Cancel", onAction: () => setModalOpen(false) }]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Modal.Section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {availableOptions.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Banner tone="info">All available markets have been added.</Banner>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                label="Select Market"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              options={availableOptions.map((o) => ({ label: o.label, value: o.value }))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={selectedCode}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={setSelectedCode}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Modal.Section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Modal>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Page>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
